#!/usr/bin/env python3
"""guard_claims - a sentence about what a guard covers is a figure, and no figure here is typed.

Session 126, 2026-08-18. `CONDITIONS-125.md` binding item 4: *extend the no-typed-figure rule to
claims about the guards.* This is that extension, and it is the class, not the instance.

THE DEFECT CLASS, STATED PLAINLY
--------------------------------
Six consecutive gauntlets on this bundle failed, and not one of them failed on a measurement.
Every blocking finding was a sentence this practice typed about its own apparatus. Session 120
wrote the rule that would have caught them - *no figure in the bundle is typed by a human* -
and sessions 123 and 124 extended it across the prose and then across `FIGURES.md`. It was never
extended to the one kind of sentence that kept failing: **claims about what the guards cover.**

Those sentences look like prose and behave like figures. "36 of 53 published errata are
registered in it, and the rest are unchecked" is a claim with a truth value that a script can
evaluate, sitting three lines below a table that already contradicted it. It survived because the
provenance guard reads *numbers* and asks whether each was fetched from a JSON field - and a
sentence can be false while every digit in it is correctly provenanced, or, as here, while it
contains a digit that was true when it was typed and is false now. The guard checked the number's
pedigree. Nobody checked the claim.

WHAT THIS DOES INSTEAD
----------------------
It asks each guard what it currently covers, renders the answer, and owns the region of
`VERSIONS.md` where claims about guards live. Two modes:

    python3 guard_claims.py --write    regenerate the block from the guards' live output
    python3 guard_claims.py --check    fail if the block on disk is not what the guards say now

`--check` is wired into the build. A session that edits a guard and forgets its changelog now
breaks the build instead of shipping a stale disclosure, and a session that hand-edits the block
breaks it too. The region is delimited and marked do-not-edit; everything outside it is ordinary
prose and this script makes no claim about it.

WHAT IT DOES NOT DO, SO NOBODY DISCOVERS IT AT THE SEVENTH GAUNTLET
------------------------------------------------------------------
- It covers the block it owns in `VERSIONS.md` and nothing else. A guard-claim written into
  `README.md` or `LETTER.md` is outside it and is exactly as unchecked as it was before. The
  honest scope is: the one document where every one of the six failures actually landed.
- It checks claims it is given a computation for. A new guard whose coverage nobody wires in here
  is unchecked, and silently so.
- The limitation claims below (the provenance guard reads digits, not number-words) are
  **demonstrated, not asserted**: the script feeds the guard a probe and reports what it did.
"""
import json
import os
import subprocess
import sys

import errata_check
import figures as F

BUNDLE = "deliverable-v0.3"
VERSIONS = os.path.join(BUNDLE, "VERSIONS.md")
BEGIN = "<!-- GUARD-CLAIMS:BEGIN - generated by guard_claims.py; do not edit by hand -->"
END = "<!-- GUARD-CLAIMS:END -->"


def P(name):
    return os.path.join(BUNDLE, name)


def _prose_files():
    return [P("README.md"), P("LETTER.md"), P("LIMITS.md"), P("VERSIONS.md")]


def facts():
    """Ask every guard what it covers, right now. No value here is read from a stored report."""
    cov = errata_check.coverage()

    prose = F.audit_prose(_prose_files(), P("FIGURE-PROVENANCE.json"))
    figs = F.audit_prose([P("FIGURES.md")], P("FIGURES-PROVENANCE.json"))

    prov_prose = json.load(open(P("FIGURE-PROVENANCE.json")))
    prov_figs = json.load(open(P("FIGURES-PROVENANCE.json")))

    # The digit limitation, demonstrated rather than claimed. The probe carries the same false
    # figure twice - once in digits, once as a word - and is put through the real guard against the
    # real provenance table. A guard that reads words would flag both. The positive control is the
    # point: if the digit half stops being flagged, the probe is broken, not the guard vindicated.
    probe = ("This bundle records 91827 events. This bundle records ninety-one thousand eight "
             "hundred and twenty-seven events.")
    probe_path = "guard-claims-wordnumber-probe.md"
    open(probe_path, "w").write(probe + "\n")
    try:
        pr = F.audit_prose([probe_path], P("FIGURE-PROVENANCE.json"))
        probe_flagged = [u["token"] for u in pr["files"][0]["unmatched"]]
    finally:
        os.remove(probe_path)

    return {
        "errata": {
            "published_accounted": cov["n_published_accounted"],
            "registered_as_wording": cov["n_registered_as_wording"],
            "reasoned_as_unregistrable": cov["n_reasoned_as_unregistrable"],
            "unaccounted": len(cov["unaccounted_published_ids"]),
            "broken_mappings": len(cov["broken_mappings"]),
        },
        "provenance_prose": {
            "files": [os.path.basename(f["file"]) for f in prose["files"]],
            "entries": len(prov_prose["figures"]),
            "unmatched": prose["n_unmatched_total"],
        },
        "provenance_figures_page": {
            "files": [os.path.basename(f["file"]) for f in figs["files"]],
            "entries": len(prov_figs["figures"]),
            "rendered_tokens": figs.get("n_rendered_tokens"),
            "unmatched": figs["n_unmatched_total"],
        },
        "word_number_probe": {
            "text": probe,
            "flagged_by_the_guard": probe_flagged,
            "digit_half_flagged": "91827" in probe_flagged,
            "word_half_flagged": any(not t.replace(",", "").isdigit() for t in probe_flagged),
        },
    }


def render(f):
    e, pp, pf = f["errata"], f["provenance_prose"], f["provenance_figures_page"]
    probe = f["word_number_probe"]
    if not probe["digit_half_flagged"]:
        word_line = ("**The probe is broken and this build should not be trusted on this point.** "
                     "A deliberately false figure in digits was NOT flagged, so the probe tests "
                     "nothing about words.")
    elif probe["word_half_flagged"]:
        word_line = ("**Probed this build, and the guard DOES read words.** The same false figure "
                     "was flagged in both spellings, so the word-number limitation earlier "
                     "versions of this file recorded no longer holds.")
    else:
        word_line = ("**Demonstrated in this build, not remembered.** The same false figure was "
                     "put through the guard twice, once as `91827` and once spelled out. The "
                     "digit form was flagged; the spelled-out form was not. A figure written as a "
                     "word still passes untouched, and the digit half is the positive control that "
                     "makes that a finding rather than a silence.")

    lines = [
        BEGIN,
        "",
        "### What the guards cover — asked of the guards, not typed",
        "",
        "*Every figure and every claim in this section is produced by `guard_claims.py` from the "
        "guards' own live output at build time; `guard_claims.py --check` fails the build if what "
        "is written here is not what the guards say. It exists because six consecutive gauntlets "
        "on this bundle failed on sentences of exactly this kind — descriptions of the apparatus "
        "that were true when typed and false when read — while every number in them was correctly "
        "provenanced. A claim about a guard is a figure.*",
        "",
        "**The prose provenance guard.** Every number in " +
        ", ".join("`" + n + "`" for n in pp["files"]) + " is fetched from a named JSON field or "
        "declared a literal with a stated reason, and recorded in `FIGURE-PROVENANCE.json` (" +
        str(pp["entries"]) + " entries). Unmatched numbers in this build: **" +
        str(pp["unmatched"]) + "**. The build refuses to complete if that is not zero.",
        "",
        "**The figures page.** `" + "`, `".join(pf["files"]) + "` is governed by a separate table, "
        "`FIGURES-PROVENANCE.json` (" + str(pf["entries"]) + " entries) — a different file from "
        "`FIGURE-PROVENANCE.json` above, and the near-identical names are a hazard this bundle has "
        "already misread once. Rendered tokens checked: **" + str(pf["rendered_tokens"]) +
        "**. Unmatched: **" + str(pf["unmatched"]) + "**.",
        "",
        "**The one limit of both.** They read digits. " + word_line,
        "",
        "**The errata check.** `errata_check.py` holds this arc's published corrections as a "
        "machine checklist and fails the build if one is live again in the bundle. Its coverage is "
        "an accounting, not a sample: **" + str(e["published_accounted"]) + "** published errata "
        "are accounted for — **" + str(e["registered_as_wording"]) + "** registered as wording the "
        "build fails on if it returns, **" + str(e["reasoned_as_unregistrable"]) + "** left out "
        "with a stated reason — with **" + str(e["unaccounted"]) + "** unaccounted and **" +
        str(e["broken_mappings"]) + "** broken mappings. What it still cannot do is unchanged: a "
        "false claim reworded escapes a phrase check.",
        "",
        END,
    ]
    return "\n".join(lines)


def _split(text):
    if BEGIN not in text or END not in text:
        return None
    head, rest = text.split(BEGIN, 1)
    body, tail = rest.split(END, 1)
    return head, BEGIN + body + END, tail


def main(argv):
    mode = argv[0] if argv else "--check"
    text = open(VERSIONS).read()
    parts = _split(text)
    fresh = render(facts())

    if mode == "--write":
        if parts is None:
            raise SystemExit(VERSIONS + " has no GUARD-CLAIMS block to write into; add the "
                             "delimiters first so the region this script owns is explicit")
        head, _, tail = parts
        open(VERSIONS, "w").write(head + fresh + tail)
        print("wrote guard-claims block into " + VERSIONS)
        return 0

    if mode == "--check":
        if parts is None:
            print("FAIL: " + VERSIONS + " has no GUARD-CLAIMS block", file=sys.stderr)
            return 1
        _, on_disk, _ = parts
        if on_disk.strip() == fresh.strip():
            print("guard claims: OK - every claim in the block matches what the guard reports now")
            return 0
        print("FAIL: the guard-claims block in " + VERSIONS + " is not what the guards say now.\n"
              "This is the defect class that killed six gauntlets. Run --write and read the diff.",
              file=sys.stderr)
        a = os.path.join(os.path.dirname(__file__) or ".", "guard-claims-expected.txt")
        open(a, "w").write(fresh + "\n")
        subprocess.call(["diff", "-u", "-", a], input=(on_disk + "\n").encode())
        return 1

    if mode == "--facts":
        print(json.dumps(facts(), indent=1))
        return 0

    raise SystemExit("usage: guard_claims.py [--check|--write|--facts]")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
