#!/usr/bin/env python3
"""receiver_series - collate every dated reading this practice has taken of the receiver's
own eleven identifiers, and write the bundle page that carries them.

Session 120, 2026-08-15. The eleven identifiers are not ours: they are the list the receiver's
own public dashboard tracks, transcribed at session 112 from the dashboard page itself and
stored unchanged in `receiver-list.txt`. They are NOT part of this arc's pre-registered window
population and are never mixed into it - they are measured as a separate list, by the same
unmodified instrument.

    python3 receiver_series.py READING.json [READING.json ...] --out deliverable

Every input is a `field-research/presence-check/1` file written by presence_check.py.
"""
import argparse
import json
import os


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("readings", nargs="+")
    ap.add_argument("--out", default="deliverable")
    a = ap.parse_args()

    reads = []
    for p in a.readings:
        d = json.load(open(p))
        if d.get("schema") != "field-research/presence-check/1":
            raise SystemExit(f"{p}: unexpected schema {d.get('schema')!r}")
        reads.append((p, d))
    reads.sort(key=lambda t: t[1]["started_utc"])

    vids = []
    for _, d in reads:
        for o in d["observations"]:
            if o["vid"] not in vids:
                vids.append(o["vid"])

    rows = []
    for vid in vids:
        row = {"vid": vid, "states": {}, "handle_returned": {}, "created_utc": None,
               "band": None}
        for p, d in reads:
            day = d["started_utc"][:10]
            for o in d["observations"]:
                if o["vid"] == vid:
                    row["states"][day] = o["state"]
                    row["handle_returned"][day] = o.get("author_unique_id")
                    row["created_utc"] = row["created_utc"] or o.get("created_utc")
                    row["band"] = row["band"] or o.get("band")
        rows.append(row)

    days = [d["started_utc"][:10] for _, d in reads]
    out = {
        "schema": "field-research/receiver-list-series/1",
        "what_this_is": ("every dated reading this practice has taken of the eleven identifiers "
                         "the receiver's own public dashboard tracks. Measured with the "
                         "unmodified instrument, from the same vantage as this practice's own "
                         "ledger, credential-free. NOT part of the pre-registered window "
                         "population and never mixed into it."),
        "list_source": ("https://playground.tiktok-audit.com/api-na/ - transcribed 2026-08-12 "
                        "(session 112) into receiver-list.txt, unchanged since"),
        "days": days,
        "readings": [{"file": os.path.basename(p),
                      "started_utc": d["started_utc"],
                      "vantage_asn": d["vantage"]["asn"],
                      "vantage_country": d["vantage"]["country"],
                      "counts": d["counts"],
                      "determinate": d["determinate"],
                      "public_absence_rate": d["public_absence_rate"],
                      "expectation": d.get("expectation_for_this_age_profile")}
                     for p, d in reads],
        "units": rows,
    }
    os.makedirs(a.out, exist_ok=True)
    json.dump(out, open(os.path.join(a.out, "receiver-eleven.json"), "w"), indent=1)

    # the markdown page that travels in the bundle
    lines = []
    lines.append("# The receiver's own eleven, measured from the public side\n")
    lines.append("*Generated by `receiver_series.py`. Every number on this page is read from "
                 "`receiver-eleven.json`, which is written directly from the instrument's own "
                 "output files. Do not hand-edit either.*\n")
    lines.append("## The readings\n")
    lines.append("| measured (UTC) | vantage | retrievable | not retrievable | indeterminate | "
                 "observed public absence | expected for this age profile |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in out["readings"]:
        c = r["counts"]
        e = r["expectation"]
        exp = ("—" if not e else
               f"{e['expected_absent_rate']:.4f} [{e['expected_lo']:.4f}, {e['expected_hi']:.4f}]")
        obs = ("—" if r["public_absence_rate"] is None
               else f"{r['public_absence_rate']:.4f} "
                    f"({c.get('NOT-RETRIEVABLE', 0)}/{r['determinate']})")
        lines.append(f"| {r['started_utc']} | {r['vantage_asn']} ({r['vantage_country']}) | "
                     f"{c.get('RETRIEVABLE', 0)} | {c.get('NOT-RETRIEVABLE', 0)} | "
                     f"{c.get('INDETERMINATE', 0)} | {obs} | {exp} |")
    lines.append("")
    lines.append("## Per identifier\n")
    lines.append("| video id | created (decoded) | age band | " + " | ".join(days) + " |")
    lines.append("|---|---|---|" + "---|" * len(days))
    for row in rows:
        lines.append(f"| `{row['vid']}` | {row['created_utc'] or '—'} | {row['band'] or '—'} | "
                     + " | ".join(row["states"].get(d, "—") for d in days) + " |")
    lines.append("")
    lines.append("**How to read this table.** `RETRIEVABLE` means the platform's credential-free "
                 "public endpoint returned a usable public record for that identifier, from this "
                 "vantage, at that moment. `NOT-RETRIEVABLE` means the endpoint refused with a "
                 "single opaque HTTP 400 — a code a synthetic identifier that never existed also "
                 "returns. **It does not mean deleted.** The expectation column is a yardstick "
                 "computed from a different, much larger population measured the same way; on "
                 "eleven identifiers it cannot separate hypotheses, and `LIMITS.md` §8 says why.")
    open(os.path.join(a.out, "receiver-eleven.md"), "w").write("\n".join(lines) + "\n")
    print(json.dumps({"days": days, "n_units": len(rows),
                      "counts": [r["counts"] for r in out["readings"]]}, indent=1))


if __name__ == "__main__":
    main()
