#!/usr/bin/env python3
"""routing_equivalence_124 - did routing FIGURES.md through the provenance guard MOVE a number?

Session 124, 2026-08-16.

The claim this session wants to make is narrow and it is the one a reviewer should distrust:
`FIGURES.md` is now built by reading the bundle's own JSON files instead of the builder's
in-memory variables, and **the tables it produces are the same tables**. A rewrite that quietly
changed a published figure while claiming to add provenance would be the worst possible outcome
of this move, so it is tested rather than asserted.

METHOD
------
Build the bundle at the SAME cut-off version 0.3.1 shipped (through 2026-08-15), so the panel is
identical, and compare the routed page cell by cell against the shipped page. Comparison is on
the numeric tokens in table rows, normalised for two rendering changes this session made
deliberately and states here rather than hides:

  * thousands separators: the routed page renders counts as `3,581`, the old page as `3581`;
  * interval brackets: `[11.17 %–13.32 %]` against `[11.17 %, 13.32 %]`.

Neither changes a value. Anything else that differs is a real difference and is printed.

WHAT THIS CANNOT SHOW
---------------------
It compares the two pages. It cannot show that either page is right about the world - that is
what the run files and the gauntlet are for. And a figure that is absent from BOTH pages is
invisible to it.
"""
import json
import re
import subprocess
import sys

# The page as version 0.3.1 shipped it, generated by the OLD in-builder method over the five-day
# panel. It is read from git (`HEAD:...deliverable-v0.3/FIGURES.md`) into this path before the
# comparison, because the working tree's copy is the rebuilt one and comparing the new generator
# against its own output would prove nothing. `SHIPPED` is passed in as argv[3].
SHIPPED = "deliverable-v0.3/FIGURES.md"
NUM = re.compile(r"(?<![A-Za-z0-9])\d[\d,]*(?:\.\d+)?")

# The two pages render scientific notation differently and deliberately: the old generator used
# python's `%.3e` ("3.083e-10"), `figures.sci` writes this arc's own house form
# ("3.083 x 10<sup>-10</sup>"). Same value, different characters, and tokenising them naively
# desynchronises every figure after the first p-value. Both forms are lifted out into their own
# comparison before the numeric streams are compared.
SCI_OLD = re.compile(r"(?<![A-Za-z0-9])(\d+(?:\.\d+)?)e([+-]?\d+)")
SCI_NEW = re.compile(r"(?<![A-Za-z0-9])(\d+(?:\.\d+)?)\s*×\s*10<sup>([+-]?\d+)</sup>")


def _lift_sci(text):
    """Return (text with scientific notation removed, the values it held as floats)."""
    vals = []

    def take(m):
        vals.append(float(m.group(1)) * 10 ** int(m.group(2)))
        return " "
    text = SCI_NEW.sub(take, text)
    text = SCI_OLD.sub(take, text)
    return text, vals


def sci_values(path):
    _, v = _lift_sci(open(path).read())
    return v


def cells(path, section=None):
    """Every numeric token of every table row, in order.

    With `section`, only rows under the `## <n>.` heading with that number - the pages are
    compared section by section, because section 6 deliberately GAINED a column (the two
    INDETERMINATE scopes, first gauntlet finding 14) and a flat comparison would desynchronise
    on it and report every later figure as changed.
    """
    out = []
    cur = None
    for line in _lift_sci(open(path).read())[0].splitlines(True):
        m = re.match(r"^##\s+(\d+)\.", line)
        if m:
            cur = int(m.group(1))
        if section is not None and cur != section:
            continue
        if not line.startswith("|") or set(line.strip()) <= set("|-: "):
            continue
        for c in [x.strip() for x in line.strip().strip("|").split("|")]:
            c = re.sub(r"`[^`]*`", " ", c)                 # identifiers are addresses, not claims
            for t in NUM.findall(c):
                out.append(t.replace(",", ""))
    return out


def prose_numbers(path):
    """Numeric tokens outside tables - the sentences that carry the page's claims."""
    out = []
    for line in _lift_sci(open(path).read())[0].splitlines(True):
        if line.startswith("|") or line.startswith("#"):
            continue
        line = re.sub(r"`[^`]*`", " ", line)
        line = re.sub(r"\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}Z)?", " ", line)
        out += [t.replace(",", "") for t in NUM.findall(line)]
    return out


def main():
    global SHIPPED
    # argv: [out_dir] [shipped_reference_page]. The reference defaults to a git extraction of the
    # original in-builder page, written to a scratch file by the caller. The bundle is always
    # rebuilt at the five-day cut-off, so the comparison is same-panel and same-method-boundary.
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "/tmp/equiv-day5"
    if len(sys.argv) > 2:
        SHIPPED = sys.argv[2]
    r = subprocess.run([sys.executable, "build_v03.py", "--out", out_dir,
                        "--cutoff", "2026-08-15T23:59:59Z", "--audit"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("equivalence build failed")

    routed = f"{out_dir}/FIGURES.md"
    per_section = {}
    diffs = []
    for s in range(1, 7):
        a_s, b_s = cells(SHIPPED, s), cells(routed, s)
        ok = a_s == b_s
        per_section[f"section_{s}"] = {"n_shipped": len(a_s), "n_routed": len(b_s),
                                       "identical": ok}
        if not ok:
            for i in range(max(len(a_s), len(b_s))):
                x = a_s[i] if i < len(a_s) else None
                y = b_s[i] if i < len(b_s) else None
                if x != y:
                    diffs.append({"section": s, "index": i, "shipped": x, "routed": y})
    per_section["section_6"]["expected_to_differ"] = (
        "yes - this section gained a column. The old page printed one INDETERMINATE count per "
        "day, over ALL units including the control arm, beside an exclusion count in section 4 "
        "that excludes the control arm, with nothing saying they were different questions "
        "(first gauntlet, finding 14). Both scopes are now printed side by side.")
    a, b = cells(SHIPPED), cells(routed)
    same = all(v["identical"] for k, v in per_section.items() if k != "section_6")

    pa, pb = prose_numbers(SHIPPED), prose_numbers(routed)
    sa, sb = sci_values(SHIPPED), sci_values(routed)
    sci_same = len(sa) == len(sb) and all(
        x == y or (y and abs(x - y) / abs(y) < 1e-6) for x, y in zip(sa, sb))

    # The three figures that were literals typed into the old generator. Each is now fetched
    # from a field; the test is whether the fetched value agrees with what was typed, ON THIS
    # PANEL. On any other panel a typed literal cannot agree by construction, which is the whole
    # reason they had to go.
    der = json.load(open(f"{out_dir}/figures-derived.json"))
    formerly_typed = {
        "balanced_panel_spread_pp": {
            "typed_into_the_old_generator": 0.0577,
            "fetched_now": round(100 * der["balanced_panel"]["range"], 4),
            "field": "figures-derived.json:balanced_panel.range",
        },
        "control_identifiers_that_do_not_resolve": {
            "typed_into_the_old_generator": 248,
            "fetched_now": der["control_arm"]["n_not_resolving_on_newest_day"],
            "field": "figures-derived.json:control_arm.n_not_resolving_on_newest_day",
        },
        "encyclopedia_language_editions": {
            "typed_into_the_old_generator": 37,
            "fetched_now": der["population"]["n_encyclopedia_language_editions"],
            "field": "figures-derived.json:population.n_encyclopedia_language_editions",
        },
    }
    for v in formerly_typed.values():
        v["agrees_on_this_panel"] = (v["fetched_now"] == v["typed_into_the_old_generator"])

    report = {
        "schema": "field-research/routing-equivalence/1",
        "question": ("does the provenance-routed FIGURES.md state the same figures as the page "
                     "version 0.3.1 shipped, on the same panel?"),
        "shipped_page": SHIPPED,
        "routed_page": routed,
        "cutoff": "2026-08-15T23:59:59Z",
        "n_table_figures_shipped": len(a),
        "n_table_figures_routed": len(b),
        "table_figures_identical_sections_1_to_5": same,
        "per_section": per_section,
        "n_scientific_notation_values": [len(sa), len(sb)],
        "scientific_notation_identical": sci_same,
        "scientific_notation_shipped": sa,
        "scientific_notation_routed": sb,
        "table_differences": diffs,
        "n_prose_figures_shipped": len(pa),
        "n_prose_figures_routed": len(pb),
        "prose_note": ("the prose around the tables was rewritten - it now states the balanced "
                       "panel's size and the raw/balanced ratio, which the old page did not - so "
                       "prose token counts are EXPECTED to differ and are reported, not asserted "
                       "equal."),
        "formerly_typed_literals": formerly_typed,
    }
    json.dump(report, open("routing-equivalence-124.json", "w"), indent=1)
    print(json.dumps({k: v for k, v in report.items()
                      if k not in ("table_differences",)}, indent=1))
    if diffs:
        print(f"\n{len(diffs)} table differences:")
        for d in diffs[:40]:
            print(f'  #{d["index"]}: shipped {d["shipped"]} -> routed {d["routed"]}')
    return 0


if __name__ == "__main__":
    sys.exit(main())
