#!/usr/bin/env python3
"""session126_sections - the two content repairs of 2026-08-18, generated and re-checkable.

`CONDITIONS-125.md` binding items 2 and 3:

  2. Close finding 3 the only way it can be closed: a dated statement of the corpus pull, or the
     9.5353-day bracket from `panel-date-125.json` stated as a limit in `LIMITS.md`, plus the
     citation-maintenance confound named as a candidate distinct from platform-side removal.
  3. Add finding 7 - the persistence result - to the bundle.

Both are new prose carrying new figures, in a session forbidden from rebuilding the bundle. So
neither is typed. Each lives in a delimited block this script owns, rendered from the JSON files
the figures come from, with `--check` re-rendering and comparing character for character - the
same discipline `guard_claims.py` applies to claims about the guards, applied here to claims
about the measurement.

    python3 session126_sections.py --write
    python3 session126_sections.py --check

It also does two things that are not blocks:

- **Copies the two sidecars into the bundle.** `panel-date-125.json` and `persistence-126.json`
  are what these sections are computed from. A limit whose evidence is not beside it is a limit a
  receiver has to take on trust, and finding 4 of the same gauntlet was precisely about claiming
  files are present when they are not.
- **Repairs the stale hash in `confirmation-record.json`** (Verifier finding N2). The old value is
  kept beside the new one with the reason, because a hash that silently changes is the thing this
  bundle exists to be able to detect.
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys

import figures as F

BUNDLE = "deliverable-v0.3"
SIDECARS = ["panel-date-125.json", "persistence-126.json"]
PROV = os.path.join(BUNDLE, "FIGURE-PROVENANCE.json")          # governs the prose
PROV_FIGURES = os.path.join(BUNDLE, "FIGURES-PROVENANCE.json")  # governs FIGURES.md
MARK = "session 126: the panel-date limit and the persistence result"

BLOCKS = {
    os.path.join(BUNDLE, "LIMITS.md"): "PANEL-DATE",
    os.path.join(BUNDLE, "FIGURES.md"): "PERSISTENCE",
}


def P(name):
    return os.path.join(BUNDLE, name)


def begin(tag):
    return "<!-- SESSION-126:" + tag + ":BEGIN - generated by session126_sections.py; do not " \
           "edit by hand -->"


def end(tag):
    return "<!-- SESSION-126:" + tag + ":END -->"


def copy_sidecars():
    out = []
    for s in SIDECARS:
        dst = P(s)
        if not os.path.exists(s):
            raise SystemExit("missing sidecar: " + s)
        if not (os.path.exists(dst) and open(dst, "rb").read() == open(s, "rb").read()):
            shutil.copyfile(s, dst)
            out.append(s)
    return out


def repair_confirmation_hash(apply=True):
    """Verifier N2: `confirmation-record.json` carries a stale sha256 for `ledger/corrections.json`.

    Verified rather than assumed. The recorded hash is the hash of the state committed at
    `49f6d6b`; the live file differs from that state in exactly one field, `generated_utc`, and
    every correction row is byte-identical. That is computed here and recorded in the file, so a
    reader does not have to take "the data is unchanged" on anyone's word.
    """
    rec_path = P("confirmation-record.json")
    rec = json.load(open(rec_path))
    src = rec["sources"]["corrections"]
    live = hashlib.sha256(open(src, "rb").read()).hexdigest()
    old = rec["sources"]["corrections_sha256"]
    if live == old:
        return {"changed": False, "sha256": live}

    prev = subprocess.run(["git", "show", "49f6d6b:drafts/2026-08-11-the-arm-that-was-missing/"
                           + src], capture_output=True)
    diff_fields, rows_identical = None, None
    if prev.returncode == 0:
        was = json.loads(prev.stdout)
        now = json.loads(open(src).read())
        diff_fields = sorted(k for k in set(was) | set(now) if was.get(k) != now.get(k))
        rows_identical = was.get("corrections") == now.get("corrections")

    if apply:
        rec["sources"]["corrections_sha256"] = live
        rec["sources"]["corrections_sha256_superseded"] = {
            "value": old,
            "was_the_hash_of": "the state committed at 49f6d6b",
            "found_by": "Verifier finding N2 at the gauntlet of 2026-08-17",
            "repaired": "2026-08-18, session 126",
            "fields_that_differ_between_the_two_states": diff_fields,
            "correction_rows_byte_identical": rows_identical,
            "why_it_drifted": ("`corrections.json` is regenerated when a measurement day closes "
                               "and restamps its own `generated_utc`, so its hash moves even when "
                               "no correction changes. Verified here rather than assumed."),
        }
        json.dump(rec, open(rec_path, "w"), indent=1)
    return {"changed": True, "sha256": live, "superseded": old,
            "fields_that_differ": diff_fields, "rows_identical": rows_identical}


def render_blocks():
    """Build each block with its OWN Figures instance, because the two files are governed by two
    different provenance tables. Merging them would put figures from `FIGURES.md` into the table
    that governs the prose - the near-identical-filename hazard this same gauntlet raised as
    finding 5."""
    fx = F.Figures(relative_to=BUNDLE)          # -> FIGURE-PROVENANCE.json, governs LIMITS.md
    fp = F.Figures(relative_to=BUNDLE)          # -> FIGURES-PROVENANCE.json, governs FIGURES.md
    pd, pe = P("panel-date-125.json"), P("persistence-126.json")

    n_files = fx.n(pd, "corpus_files_examined")
    n_stamped = fx.n(pd, "corpus_files_carrying_any_timestamp")
    lo = fx.raw(pd, "lower_bound_utc")
    hi = fx.raw(pd, "upper_bound_utc")
    days = fx.num(pd, "bracket_days")

    panel = "\n".join([
        begin("PANEL-DATE"),
        "",
        "## 11. The panel has no recorded construction date, and this is the width of that gap",
        "",
        "*Added 2026-08-18. This is the blocking objection of the gauntlet of 2026-08-17, conceded "
        "in full. It is a property of the sampling frame, not a wording defect, and it cannot be "
        "closed by re-measuring anything.*",
        "",
        "Every age-banded figure in this bundle rests on a panel of cited identifiers, and **no "
        "record of when that panel was collected exists anywhere in this arc.** " + n_files +
        " corpus files were examined and " + n_stamped + " carries any timestamp at all — and that "
        "one is the *newest citation in the pool*, not the moment the pool was pulled.",
        "",
        "The record can only bracket it. The pull is at or after **" + lo + "** (it cannot precede "
        "its own newest row) and before **" + hi + "** (the first completed run over the panel): a "
        "window of **" + days + " days**. Until a collection time is recovered, that bracket is "
        "the honest statement of this panel's date, and it travels with any reuse of an age-band "
        "cell, an age-gradient row or an expectation figure.",
        "",
        "**And a confound is open that this bracket does not close.** Encyclopedia editions prune "
        "and archive-fix dead citations, and they do so at rates that are themselves a function of "
        "how long a citation has sat — *the same axis the age table is built on*. So a rising "
        "absence rate with age is consistent with two different stories that this bundle cannot "
        "separate: videos going away, or citation lists being maintained. **This is a candidate "
        "explanation distinct from platform-side removal, and no robustness check in this arc "
        "addresses it.** The arithmetic is not in question; the representativeness is. The age "
        "gradient is what this specific, undated snapshot showed on the dates measured, and it is "
        "**not** a general yardstick for cited videos of a given age.",
        "",
        "The asymmetry is worth stating against ourselves: this arc dates its reference clock to "
        "the second, measured a bookkeeping drift in that clock to four decimals, and published a "
        "table of how far it moves per month — while the clock behind the population every one of "
        "those figures rests on was never written down.",
        "",
        end("PANEL-DATE"),
    ])

    n_panel = fp.n(pe, "n_panel_non_control")
    n_ever = fp.n(pe, "n_ever_absent")
    n_all6 = fp.n(pe, "n_absent_on_all_six_days")
    p_all6 = fp.pct(pe, "frac_absent_on_all_six_days", dp=2)
    n_meas = fp.n(pe, "n_absent_on_every_day_measured")
    p_meas = fp.pct(pe, "frac_absent_on_every_day_measured", dp=2)
    n_ind = fp.n(pe, "n_never_retrievable_but_broken_only_by_indeterminate")
    n_multi = fp.n(pe, "n_units_with_more_than_one_determinate_state")

    persistence = "\n".join([
        begin("PERSISTENCE"),
        "",
        "## How stable an absence is, across the whole panel",
        "",
        "*Added " + fp.lit("2026-08-18", "the date this section was added") + ". Found by the adversary at the gauntlet of " + fp.lit("2026-08-17", "the date of the sixth gauntlet, at which this result was raised") + ", in this "
        "practice's own series file, which had sat in this repository for six days without anyone "
        "reading it this way. It is reported because it strengthens the work, and it is reported "
        "with the definition problem it arrived with.*",
        "",
        "The bundle's headline confirmation evidence is a small one: every apparent state change "
        "between two days was immediately re-requested five times, and the record says how many "
        "survived. That is " + fp.count(P("confirmation-record.json"), "readings",
                                        "the size of the immediate-re-request record: one entry "
                                        "per apparent state change put through five re-requests") +
        " events, and the bundle says so. The same series carries a second, independent and much "
        "larger form of confirmation, which the bundle never reported: an identifier absent on "
        "every one of six daily passes has had that absence re-observed five more times, at "
        "24-hour spacing.",
        "",
        "Of the **" + n_panel + "** non-control identifiers, **" + n_ever + "** were ever read as "
        "absent on a determinate day. Of those:",
        "",
        "| Reading | Count | Share of ever-absent |",
        "|---|---|---|",
        "| Absent on **all six days** (an `INDETERMINATE` day breaks it) | " + n_all6 + " | " +
        p_all6 + " |",
        "| Absent on **every day it was measured** (`INDETERMINATE` days excluded, as this arc "
        "treats them everywhere else) | " + n_meas + " | " + p_meas + " |",
        "",
        "The gap between the two rows is **" + n_ind + "** identifiers whose only non-absent "
        "readings are `INDETERMINATE`, plus **" + n_multi + "** that genuinely showed both states "
        "across the six days. **Both rows are printed because a single number here would be a "
        "choice presented as a fact**; the stricter one is the conservative figure and is the one "
        "to quote if only one is quoted.",
        "",
        "**What this is not.** It is not an immediate re-request, and it is weaker evidence than "
        "one. Repeated absence at 24-hour spacing from a single vantage cannot separate a "
        "persistent platform state from a persistent network or endpoint condition, and it says "
        "nothing at all about identifiers that were never absent. It does not make a single "
        "refusal trustworthy — the arc's own confirmation record refutes that, and the version of "
        "this bundle which argued it was withheld. What it does say is narrower: **an absence that "
        "this instrument reports on six separate days is not, on this panel, usually a flicker.**",
        "",
        end("PERSISTENCE"),
    ])
    return {P("LIMITS.md"): panel, P("FIGURES.md"): persistence}, fx, fp


def _splice(path, tag, block, write):
    text = open(path).read()
    b, e = begin(tag), end(tag)
    if b in text and e in text:
        head, rest = text.split(b, 1)
        _, tail = rest.split(e, 1)
        new = head + block + tail
        current = b + rest.split(e, 1)[0] + e
    else:
        new = text.rstrip("\n") + "\n\n" + block + "\n"
        current = None
    if write:
        open(path, "w").write(new)
    return current


def main(argv):
    mode = argv[0] if argv else "--check"
    if mode not in ("--check", "--write"):
        raise SystemExit("usage: session126_sections.py [--check|--write]")
    write = mode == "--write"

    if write:
        copied = copy_sidecars()
        rep = repair_confirmation_hash(apply=True)
        print("sidecars copied into the bundle: " + (", ".join(copied) or "none (already current)"))
        print("confirmation-record corrections_sha256: "
              + ("repaired -> " + rep["sha256"] if rep["changed"] else "already current"))

    blocks, fx, fp = render_blocks()
    ok = True
    for path, tag in BLOCKS.items():
        current = _splice(path, tag, blocks[path], write)
        if not write:
            if current is None:
                print("FAIL: " + path + " has no SESSION-126:" + tag + " block", file=sys.stderr)
                ok = False
            elif current.strip() != blocks[path].strip():
                print("FAIL: the SESSION-126:" + tag + " block in " + path
                      + " is not what the data says now.", file=sys.stderr)
                ok = False
        else:
            print("wrote SESSION-126:" + tag + " into " + path)

    if write:
        for table, inst in ((PROV, fx), (PROV_FIGURES, fp)):
            prov = json.load(open(table))
            # idempotent: this session's entries are replaced, never stacked, so re-running
            # --write cannot inflate n_figures.
            prov["figures"] = [f for f in prov["figures"]
                               if not f.get("note", "").startswith(MARK)]
            added = []
            for f in inst.provenance()["figures"]:
                f["note"] = MARK + ("; " + f["note"] if f["note"] else "")
                added.append(f)
            prov["figures"].extend(added)
            prov["n_figures"] = len(prov["figures"])
            json.dump(prov, open(table, "w"), indent=1)
            print("provenance: " + str(len(added)) + " figures into "
                  + os.path.basename(table) + "; n_figures is now " + str(prov["n_figures"]))
        return 0

    if ok:
        print("session-126 sections: OK - both blocks match what their data says now")
        return 0
    print("Run --write and read the diff.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
