#!/usr/bin/env python3
"""make_blind_input.py — build the file the second readers see, and nothing more.

The whole point of this script is subtraction. `data.json` carries, for every case, the
original builder's `in_population` verdict, the one-line reason for it, the blind
verdict-reader's label and rationale, and the machine's. A second reader that sees any of
those is not a second reader.

What survives into `blind-input.json`: `case_id`, `title`, `excerpt`. In an order shuffled
by `random.Random(88)` — the session number, fixed in RULE.md §2 before this ran — so that
the original 1..60 ordering, which is the key `build_data.py` maps its per-position reasons
onto, is not handed to the reader for free.

Deterministic: same input, same seed, byte-identical output. Run with --check to assert that
against the committed file instead of rewriting it.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "works" / "2026-08-03-where-the-reader-declines" / "data.json"
OUT = Path(__file__).resolve().parents[1] / "blind-input.json"

SEED = 88  # RULE.md §2, fixed before this script was first run

# Every key in a case record. Anything not in KEEP is a judgement about the case and is
# withheld; the assertion below fails if data.json ever grows a key this script has not
# been taught to classify, rather than letting it leak through.
KEEP = ("case_id", "title", "excerpt")
WITHHOLD = (
    "arxiv",
    "excerpt_sha256",
    "exclusion_reason",
    "gold",
    "in_population",
    "machine",
    "population_reason",
    "position",
    # Added to data.json by the correction this study forced, AFTER blind-input.json was
    # generated. Listed so `--check` still reproduces the file the readers actually saw;
    # withheld for the same reason as everything else here — they are judgements about the
    # case. Found by the Verifier (F4), 2026-08-04.
    "in_population_second_readers",
    "in_population_status",
)


def build() -> dict:
    cases = json.loads(SOURCE.read_text())["cases"]
    for c in cases:
        unknown = set(c) - set(KEEP) - set(WITHHOLD)
        if unknown:
            raise SystemExit(f"unclassified key(s) in {c.get('case_id')}: {sorted(unknown)}")
    blind = [{k: c[k] for k in KEEP} for c in cases]
    random.Random(SEED).shuffle(blind)
    return {
        "_note": (
            "Sixty published arXiv abstracts. Title and excerpt only: every judgement any "
            "reader has previously made about these cases is withheld. Shuffled with seed "
            f"{SEED}. Generated by scripts/make_blind_input.py; see RULE.md."
        ),
        "seed": SEED,
        "n": len(blind),
        "cases": blind,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the committed file reproduces")
    args = ap.parse_args()
    text = json.dumps(build(), indent=2, ensure_ascii=False) + "\n"
    if args.check:
        have = OUT.read_text()
        print("REPRODUCES" if have == text else "DIFFERS")
        raise SystemExit(0 if have == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(json.loads(text)['cases'])} cases)")


if __name__ == "__main__":
    main()
