#!/usr/bin/env python3
"""table_133.py — print INCREMENT-21.md's population table FROM the artifact.

WHY THIS EXISTS (2026-08-23, session 133)
-----------------------------------------
The independent recomputation of this session's own increment found its population table
wrong in 4 of 12 rows against the JSON the table cites as its source — 51 against 52, 52
against 53, 719 against 720, 1,581 against 1,585 — because the table was typed from an
EARLIER run of the audit and never re-typed when the audit was re-run. The same two stale
figures had also been copied into a second file's docstring.

That is exactly the defect `tools/record_ceiling_check.py`'s own docstring was written
about: *"a hand-carried number describing a document that is still being written is a
claim that cannot be true at the moment it is made."* This practice found it in its own
surfaces three sessions running, built a script so it would stop, and then hand-carried
numbers into a document about hand-carried numbers.

So the table is generated. Regenerate it whenever the audit is re-run.

USAGE
    python3 tools/convergence/table_133.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "convergence-audit-133.json")) as fh:
    d = json.load(fh)

print("*Generated by `tools/convergence/table_133.py` from "
      "`tools/convergence/convergence-audit-133.json`; never typed by hand.*")
print()
print("Tree this report is good for: `%s`" % d["tree_sha256_this_report_is_good_for"])
print()
print("| # | check | invocation | reads | dirs listed | writes kept | containment | convergence |")
print("|---|---|---|---|---|---|---|---|")
for i, c in enumerate(d["checks"], 1):
    kept = c.get("writes_still_present_at_exit") or []
    tr = c.get("writes_removed_before_exit") or []
    w = str(len(kept)) + (" (+%d removed)" % len(tr) if tr else "")
    print("| %d | `%s` | `%s` | %s | %s | %s | `%s` | `%s` |" % (
        i, c["id"], c.get("invocation", "").replace("|", "\\|"),
        c.get("repo_files_read"), len(c.get("repo_dirs_listed") or []), w,
        c.get("verdict_containment"), c.get("verdict_convergence")))
print()
print("Containment counts: `%s`" % json.dumps(d["counts"], sort_keys=True))
print()
print("Convergence counts: `%s`" % json.dumps(d["convergence_counts"], sort_keys=True))
