#!/usr/bin/env python3
"""A1 — measure the `wikimedia-fallback` specimen supply inside the anchor window.

The pre-registration (README §"Specimen collection") names two specimen sources in
priority order: the provider's own published example gallery (`curated-source`), and
Wikimedia Commons uploads "whose file-page upload date falls inside the anchor window"
(`wikimedia-fallback`), taken in upload-date order.

This script answers one question, offline-reproducibly: **for each per-generator Commons
category, what is the most recent file in it, and does any file fall on or after the
seam date 2026-08-02?** It does not select specimens; it measures whether the fallback
route has anything in it at all at day 0.

Method: MediaWiki API, `list=categorymembers`, `cmtype=file`, `cmsort=timestamp`,
`cmdir=desc`. NOTE ON WHAT THE TIMESTAMP IS: `cmsort=timestamp` sorts by the time the
page was ADDED TO THE CATEGORY, which for a freshly uploaded, freshly categorised file
is the upload time, but for an older file re-categorised later is not. It is therefore
an UPPER BOUND on recency: if the newest category-addition predates the seam, no file in
that category can have been uploaded after the seam *and* categorised, which is the
condition the fallback rule needs. Where a candidate did fall in the window, the exact
upload date would then be read from `prop=imageinfo` before selection. None did.

Deterministic given the API's state at run time; the run's output is committed with its
date.
"""
import json
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

UA = "field-research/meridian (research; github.com/frankbueltge/field-research)"
API = "https://commons.wikimedia.org/w/api.php?"
SEAM = "2026-08-02"

# Per-generator categories, chosen to cover both pre-registered strata: providers on the
# Code's Section 1 signatory list, and providers absent from it. Plus the broadest
# umbrella category, which bounds the whole route.
CATEGORIES = [
    "Category:Images generated by Gemini",
    "Category:Images generated by Imagen",
    "Category:Nano Banana",
    "Category:Images generated by GPT Image 2",
    "Category:Images generated by GPT Image 1.5",
    "Category:Images generated by GPT Image 1",
    "Category:Images generated by Image Creator by Microsoft Bing",
    "Category:Images generated by Grok",
    "Category:Midjourney",
    "Category:Stable Diffusion",
    "Category:AI-generated images",
]


def api(**params):
    params.setdefault("format", "json")
    params.setdefault("action", "query")
    req = urllib.request.Request(API + urllib.parse.urlencode(params),
                                 headers={"User-Agent": UA})
    return json.load(urllib.request.urlopen(req, timeout=90))


def newest(category, tries=3):
    for attempt in range(tries):
        try:
            d = api(list="categorymembers", cmtitle=category, cmtype="file",
                    cmsort="timestamp", cmdir="desc", cmlimit=8,
                    cmprop="title|timestamp")
            return [{"timestamp": m.get("timestamp"), "title": m["title"]}
                    for m in d["query"]["categorymembers"]]
        except Exception as exc:  # rate limiting is real; back off and say so
            if attempt == tries - 1:
                return {"error": f"{type(exc).__name__}: {exc}"}
            time.sleep(6)


def main():
    out = {"probe": "wikimedia-fallback specimen supply at anchor A1",
           "seam": SEAM, "api": API, "sort": "cmsort=timestamp (category-addition time)",
           "categories": {}}
    for c in CATEGORIES:
        out["categories"][c] = newest(c)
        time.sleep(4)
    in_window = []
    for c, members in out["categories"].items():
        if isinstance(members, dict):
            continue
        for m in members:
            if m["timestamp"] and m["timestamp"][:10] >= SEAM:
                in_window.append({"category": c, **m})
    out["files_at_or_after_seam"] = in_window
    out["files_at_or_after_seam_count"] = len(in_window)
    dest = Path(__file__).resolve().parent.parent / "sources" / "commons-window-probe.json"
    dest.write_text(json.dumps(out, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
                    encoding="utf-8")
    print(f"{len(in_window)} file(s) at or after {SEAM}; written to {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
