#!/usr/bin/env python3
"""Where the byline goes: conference authors vs arXiv authors, and whether the arXiv version
says the paper was AI-led. Session 171, 2026-09-26. Added after the kill condition K1 fired,
so it is DESCRIPTIVE and was not pre-registered; the terms searched are fixed in this file.
"""
import hashlib
import html
import json
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fetch                                                          # noqa: E402

WORK = sys.argv[1]
TERMS = ["Agents4Science", "AI Contribution", "AI-generated", "AI-authored", "AI-led",
         "AI agent as", "generated by AI", "written by", "primarily authored", "first author"]


def clean(x):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", x))).strip()


def main():
    d = json.load(open(os.path.join(WORK, "match.json")))
    out = []
    for p in d["papers"]:
        if not p.get("arxiv"):
            continue
        st, page = fetch.get(f"https://arxiv.org/abs/{p['arxiv']}")
        au = re.search(r'<div class="authors">(.*?)</div>', page, re.S)
        cm = re.search(r'<td class="tablecell comments[^"]*">(.*?)</td>', page, re.S)
        ab = re.search(r'<blockquote class="abstract mathjax">(.*?)</blockquote>', page, re.S)
        hv = re.search(r'\[v(\d+)\]', page)
        vers = re.findall(r'<strong>\[v(\d+)\]</strong>', page)
        rec = {"openreview": p["openreview"], "arxiv": p["arxiv"],
               "conference_authors": p["authors"],
               "arxiv_authors": clean(au.group(1)).replace("Authors:", "").strip() if au else None,
               "arxiv_comments": clean(cm.group(1)) if cm else None,
               "arxiv_abstract_first_sentence": re.split(r"(?<=\.)\s", clean(ab.group(1)).replace(
                   "Abstract:", "").strip())[0] if ab else None,
               "conference_blurb_first_sentence": re.split(r"(?<=\.)\s", p.get("blurb") or "")[0],
               "arxiv_versions": len(vers)}
        hp = os.path.join(WORK, "html", p["arxiv"] + ".html")
        if os.path.exists(hp):
            full = clean(open(hp, encoding="utf-8").read())
            hits = {}
            for t in TERMS:
                ms = [full[max(0, m.start() - 90):m.end() + 90] for m in
                      re.finditer(re.escape(t), full, re.I)]
                if ms:
                    hits[t] = {"count": len(ms), "first": ms[0]}
            rec["fulltext_terms"] = hits
        out.append(rec)
        time.sleep(3)
    json.dump(out, open(os.path.join(WORK, "byline.json"), "w"), indent=1, ensure_ascii=False)
    for r in out:
        print(json.dumps(r, ensure_ascii=False)[:1500])
        print()


if __name__ == "__main__":
    main()
